// Generated by scripts/extract-bodies.mjs. Do not edit by hand.
export const generatedPages = [
  {
    "route": "/about",
    "htmlPath": "about.html",
    "title": "Notre mission | EVplug"
  },
  {
    "route": "/approved-installer-training",
    "htmlPath": "approved-installer-training.html",
    "title": "Approved domestic installer training | Podpoint"
  },
  {
    "route": "/built-environment-enquiry",
    "htmlPath": "built-environment-enquiry.html",
    "title": "Built Environment Enquiry | Podpoint"
  },
  {
    "route": "/business/built-environment-charging",
    "htmlPath": "business/built-environment-charging.html",
    "title": "Built Environment EV Charging | Pod"
  },
  {
    "route": "/business/commercial-charging",
    "htmlPath": "business/commercial-charging.html",
    "title": "Commercial EV Charging for Business | Podpoint"
  },
  {
    "route": "/business/fleet-charging",
    "htmlPath": "business/fleet-charging.html",
    "title": "Home Fleet charging solutions | Pod"
  },
  {
    "route": "/business/workplace-charging",
    "htmlPath": "business/workplace-charging.html",
    "title": "Workplace EV charging | Pod"
  },
  {
    "route": "/case-studies",
    "htmlPath": "case-studies.html",
    "title": "Case studies overview | Podpoint"
  },
  {
    "route": "/case-studies/merchant-taylors-school",
    "htmlPath": "case-studies/merchant-taylors-school.html",
    "title": "Merchant Taylors' School: Case study | Podpoint"
  },
  {
    "route": "/case-studies/skanska",
    "htmlPath": "case-studies/skanska.html",
    "title": "Skanska: Case study | Podpoint"
  },
  {
    "route": "/contact-us",
    "htmlPath": "contact-us.html",
    "title": "Contactez-nous | EVplug"
  },
  {
    "route": "/faq",
    "htmlPath": "faq.html",
    "title": "FAQ | Podpoint"
  },
  {
    "route": "/general-terms-and-conditions",
    "htmlPath": "general-terms-and-conditions.html",
    "title": "Pod | General Ts and Cs"
  },
  {
    "route": "/guides",
    "htmlPath": "guides.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guides/2035-diesel-and-petrol-car-ban-in-the-uk-everything-you-need-to-know",
    "htmlPath": "guides/2035-diesel-and-petrol-car-ban-in-the-uk-everything-you-need-to-know.html",
    "title": "2030 diesel and petrol car ban in the UK: Everything you need to know | Pod"
  },
  {
    "route": "/guides/an-ev-drivers-guide-to-tyres",
    "htmlPath": "guides/an-ev-drivers-guide-to-tyres.html",
    "title": "An EV Driver's Guide to Tyres | Pod"
  },
  {
    "route": "/guides/are-evs-heavier-traditional-ice-vehicles",
    "htmlPath": "guides/are-evs-heavier-traditional-ice-vehicles.html",
    "title": "Are EVs Heavier Than Traditional ICE Vehicles? | Podpoint"
  },
  {
    "route": "/guides/can-i-take-my-ev-charger-when-i-move",
    "htmlPath": "guides/can-i-take-my-ev-charger-when-i-move.html",
    "title": "Can I Take My EV Charger When I Move? | Pod"
  },
  {
    "route": "/guides/charging-electric-car-at-home",
    "htmlPath": "guides/charging-electric-car-at-home.html",
    "title": "Everything You Need to Know About Charging an Electric Car at Home | Pod"
  },
  {
    "route": "/guides/charging-ev-without-home-charger",
    "htmlPath": "guides/charging-ev-without-home-charger.html",
    "title": "How to Charge if You Can't Get a Home EV Charger | Pod"
  },
  {
    "route": "/guides/choosing-ev-charging-cable",
    "htmlPath": "guides/choosing-ev-charging-cable.html",
    "title": "Choosing the Best EV Charging Cable for Your Car | Pod"
  },
  {
    "route": "/guides/complete-guide-on-ev-charging",
    "htmlPath": "guides/complete-guide-on-ev-charging.html",
    "title": "Complete guide on EV charging | Pod"
  },
  {
    "route": "/guides/couples-guide-to-going-electric",
    "htmlPath": "guides/couples-guide-to-going-electric.html",
    "title": "The Eco-Conscious Couple's Guide to Going Electric Together | Podpoint"
  },
  {
    "route": "/guides/do-electric-cars-lose-range-in-cold-weather",
    "htmlPath": "guides/do-electric-cars-lose-range-in-cold-weather.html",
    "title": "How to charge your EV in cold weather | Pod"
  },
  {
    "route": "/guides/driving-electric-with-pets",
    "htmlPath": "guides/driving-electric-with-pets.html",
    "title": "Driving Electric with Pets: A Sustainable Lifestyle Guide for Animal Lovers | Podpoint"
  },
  {
    "route": "/guides/electric-car-vs-petrol-car-cost-comparison",
    "htmlPath": "guides/electric-car-vs-petrol-car-cost-comparison.html",
    "title": "Electric Car vs Petrol Car: Cost Comparison In 2026 | Pod"
  },
  {
    "route": "/guides/ev-charger-home-installation-process",
    "htmlPath": "guides/ev-charger-home-installation-process.html",
    "title": "How to Prepare for Home EV Charger Installation | Pod"
  },
  {
    "route": "/guides/ev-charging-business-models",
    "htmlPath": "guides/ev-charging-business-models.html",
    "title": "Business Models for Commercial Electric Vehicle Charging | Pod"
  },
  {
    "route": "/guides/ev-connector-types-speed",
    "htmlPath": "guides/ev-connector-types-speed.html",
    "title": "EV Charging Connector Types and Speeds | Pod"
  },
  {
    "route": "/guides/ev-journey-planner",
    "htmlPath": "guides/ev-journey-planner.html",
    "title": "How to Plan a road trip with an EV | Pod"
  },
  {
    "route": "/guides/home-charger-benefits",
    "htmlPath": "guides/home-charger-benefits.html",
    "title": "Do You Need a Dedicated Home Charger? | Pod"
  },
  {
    "route": "/guides/how-can-i-charge-my-ev-with-no-emissions",
    "htmlPath": "guides/how-can-i-charge-my-ev-with-no-emissions.html",
    "title": "How Can I Charge my EV Without Emissions? | Podpoint"
  },
  {
    "route": "/guides/how-pod-rewards-works",
    "htmlPath": "guides/how-pod-rewards-works.html",
    "title": "How Pod Rewards works: Get paid to charge your electric vehicle | Podpoint"
  },
  {
    "route": "/guides/how-to-access-public-ev-charging",
    "htmlPath": "guides/how-to-access-public-ev-charging.html",
    "title": "How to Access Public Charging Points | Pod"
  },
  {
    "route": "/guides/how-to-charge-electric-car",
    "htmlPath": "guides/how-to-charge-electric-car.html",
    "title": "How to Charge an Electric Car | Pod"
  },
  {
    "route": "/guides/how-to-make-your-ev-part-of-a-zero-waste-lifestyle",
    "htmlPath": "guides/how-to-make-your-ev-part-of-a-zero-waste-lifestyle.html",
    "title": "How to Make Your EV Part of a Zero-Waste Lifestyle | Podpoint"
  },
  {
    "route": "/guides/how-to-talk-about-making-the-switch",
    "htmlPath": "guides/how-to-talk-about-making-the-switch.html",
    "title": "How to talk about making the switch | Podpoint"
  },
  {
    "route": "/guides/optimise-ev-range",
    "htmlPath": "guides/optimise-ev-range.html",
    "title": "How to Optimise the Range of Your Electric Car | Pod"
  },
  {
    "route": "/guides/solar-charge-electric-cars",
    "htmlPath": "guides/solar-charge-electric-cars.html",
    "title": "Can you use solar panels to charge electric cars? | Pod"
  },
  {
    "route": "/guides/tethered-vs-untethered-ev-charger-which-is-the-best",
    "htmlPath": "guides/tethered-vs-untethered-ev-charger-which-is-the-best.html",
    "title": "Tethered vs Untethered EV Charger: Which is the Best? | Pod"
  },
  {
    "route": "/guides/the-ultimate-guide-to-taking-your-ev-to-summer-festivals",
    "htmlPath": "guides/the-ultimate-guide-to-taking-your-ev-to-summer-festivals.html",
    "title": "Taking your EV to summer festivals | Podpoint"
  },
  {
    "route": "/guides/what-is-smart-ev-charging",
    "htmlPath": "guides/what-is-smart-ev-charging.html",
    "title": "Smart charging explained: A simple guide for every EV driver | Pod"
  },
  {
    "route": "/guides/workplace-charging-scheme",
    "htmlPath": "guides/workplace-charging-scheme.html",
    "title": "Workplace Charging Scheme | Pod"
  },
  {
    "route": "/guides/workplace-charging-scheme-state-funded-schools",
    "htmlPath": "guides/workplace-charging-scheme-state-funded-schools.html",
    "title": "Workplace Charging Scheme for State-Funded Schools | Pod"
  },
  {
    "route": "/guides02e4",
    "htmlPath": "guides02e4.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guides235c",
    "htmlPath": "guides235c.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guides2679",
    "htmlPath": "guides2679.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guides4658",
    "htmlPath": "guides4658.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guides9ba9",
    "htmlPath": "guides9ba9.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guidesa7f1",
    "htmlPath": "guidesa7f1.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guidesaf4d",
    "htmlPath": "guidesaf4d.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guidesc575",
    "htmlPath": "guidesc575.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guidesfdb0",
    "htmlPath": "guidesfdb0.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/guidesfdfa",
    "htmlPath": "guidesfdfa.html",
    "title": "Guides | Podpoint"
  },
  {
    "route": "/home-fleet-enquiry-form",
    "htmlPath": "home-fleet-enquiry-form.html",
    "title": "Home Fleet Enquiry Form | Podpoint"
  },
  {
    "route": "/home/home-charging",
    "htmlPath": "home/home-charging.html",
    "title": "Home EV chargers & installation included | Pod"
  },
  {
    "route": "/installation",
    "htmlPath": "installation.html",
    "title": "Installation de bornes EV | EVplug Maroc"
  },
  {
    "route": "/join",
    "htmlPath": "join.html",
    "title": "Transition electrique | EVplug"
  },
  {
    "route": "/legal/app-terms-of-use",
    "htmlPath": "legal/app-terms-of-use.html",
    "title": "Pod Point Mobile App EULA Terms and Conditions | Podpoint"
  },
  {
    "route": "/legal/cookies-policy",
    "htmlPath": "legal/cookies-policy.html",
    "title": "Cookies Policy | Podpoint"
  },
  {
    "route": "/legal/home-app-privacy-notice",
    "htmlPath": "legal/home-app-privacy-notice.html",
    "title": "Home App Privacy Notice | Podpoint"
  },
  {
    "route": "/legal/home-charger-terms-of-sale",
    "htmlPath": "legal/home-charger-terms-of-sale.html",
    "title": "Pod Point Home Charger Terms of Sale | Podpoint"
  },
  {
    "route": "/legal/installer-app-terms-of-use",
    "htmlPath": "legal/installer-app-terms-of-use.html",
    "title": "Pod Point Installer App Terms of Use | Podpoint"
  },
  {
    "route": "/legal/installer-training-terms-and-conditions",
    "htmlPath": "legal/installer-training-terms-and-conditions.html",
    "title": "Pod Point Installer Training Terms & Conditions | Podpoint"
  },
  {
    "route": "/legal/modern-slavery-statement",
    "htmlPath": "legal/modern-slavery-statement.html",
    "title": "Pod Point Modern Slavery Statement"
  },
  {
    "route": "/legal/pod-affiliate-discounts-terms",
    "htmlPath": "legal/pod-affiliate-discounts-terms.html",
    "title": "Pod Affiliate Discounts Terms and Conditions | Podpoint"
  },
  {
    "route": "/legal/pod-drive-terms-and-conditions",
    "htmlPath": "legal/pod-drive-terms-and-conditions.html",
    "title": "Pod Drive Terms and Conditions | Podpoint"
  },
  {
    "route": "/legal/pod-rewards-terms-and-conditions",
    "htmlPath": "legal/pod-rewards-terms-and-conditions.html",
    "title": "Pod Rewards terms and conditions | Podpoint"
  },
  {
    "route": "/legal/pod-warranty-statement",
    "htmlPath": "legal/pod-warranty-statement.html",
    "title": "Pod Product Warranty Statement | Podpoint"
  },
  {
    "route": "/legal/podenergy-plug-power-tariff-offer-terms-and-conditions",
    "htmlPath": "legal/podenergy-plug-power-tariff-offer-terms-and-conditions.html",
    "title": "Pod Point Plug & Power tariff offer terms and conditions | Podpoint"
  },
  {
    "route": "/legal/policies",
    "htmlPath": "legal/policies.html",
    "title": "Our Policies | Podpoint"
  },
  {
    "route": "/legal/privacy-and-cookies-policy",
    "htmlPath": "legal/privacy-and-cookies-policy.html",
    "title": "Pod Point Privacy Notices and Cookies Policies | Podpoint"
  },
  {
    "route": "/legal/privacy-notice",
    "htmlPath": "legal/privacy-notice.html",
    "title": "Privacy Notice | Podpoint"
  },
  {
    "route": "/legal/public-charger-terms-of-use",
    "htmlPath": "legal/public-charger-terms-of-use.html",
    "title": "Pod Point Public Charger Network Terms of Use | Podpoint"
  },
  {
    "route": "/legal/returns-and-refunds",
    "htmlPath": "legal/returns-and-refunds.html",
    "title": "Returns and Refunds Policy | Podpoint"
  },
  {
    "route": "/legal/website-acceptable-use-policy",
    "htmlPath": "legal/website-acceptable-use-policy.html",
    "title": "Pod Point Website Acceptable Use Policy | Podpoint"
  },
  {
    "route": "/legal/website-terms-of-use",
    "htmlPath": "legal/website-terms-of-use.html",
    "title": "Pod Website Terms of Use | Podpoint"
  },
  {
    "route": "/news",
    "htmlPath": "news.html",
    "title": "Actualites | EVplug"
  },
  {
    "route": "/news/pod-and-knowles-fleet-launch-salary-sacrifice-home-ev-charging-solution",
    "htmlPath": "news/pod-and-knowles-fleet-launch-salary-sacrifice-home-ev-charging-solution.html",
    "title": "Pod and Knowles Fleet launch salary sacrifice home EV charging solution | Podpoint"
  },
  {
    "route": "/news/pod-and-salsac-partner-offer-home-ev-charging-through-salary-sacrifice",
    "htmlPath": "news/pod-and-salsac-partner-offer-home-ev-charging-through-salary-sacrifice.html",
    "title": "Pod and SalSac partner to offer home EV charging through salary sacrifice | Podpoint"
  },
  {
    "route": "/news/pod-announces-pod-rewards-pay-customers-smart-charging-their-evs",
    "htmlPath": "news/pod-announces-pod-rewards-pay-customers-smart-charging-their-evs.html",
    "title": "Pod announces Pod Rewards to pay customers for smart charging their EVs | Podpoint"
  },
  {
    "route": "/news/pod-launches-home-fleet-solution-businesses-simplify-ev-fleet-management",
    "htmlPath": "news/pod-launches-home-fleet-solution-businesses-simplify-ev-fleet-management.html",
    "title": "Pod launches Home Fleet solution for businesses to simplify EV fleet management | Podpoint"
  },
  {
    "route": "/news/pod-launches-pod-power-edf-7-hour-peak-ev-tariff",
    "htmlPath": "news/pod-launches-pod-power-edf-7-hour-peak-ev-tariff.html",
    "title": "Pod launches Pod Power by EDF, a 7-hour off-peak EV tariff | Podpoint"
  },
  {
    "route": "/news/pod-offers-home-ev-charging-no-upfront-cost-through-pod-drive-subscription-promotion",
    "htmlPath": "news/pod-offers-home-ev-charging-no-upfront-cost-through-pod-drive-subscription-promotion.html",
    "title": "Pod offers home EV charging with no upfront cost, through Pod Drive subscription promotion | Podpoint"
  },
  {
    "route": "/news/pod-partners-leasing-make-home-charging-easy-and-affordable-its-ev-customers",
    "htmlPath": "news/pod-partners-leasing-make-home-charging-easy-and-affordable-its-ev-customers.html",
    "title": "Pod partners with Leasing.com to make home charging easy and affordable for its EV customers | Podpoint"
  },
  {
    "route": "/news/pod-partners-uber-deliver-discounted-home-ev-charging",
    "htmlPath": "news/pod-partners-uber-deliver-discounted-home-ev-charging.html",
    "title": "Pod partners with Uber to deliver discounted home EV charging for drivers | Podpoint"
  },
  {
    "route": "/news/pod-partners-zapmap-public-ev-charging-payments",
    "htmlPath": "news/pod-partners-zapmap-public-ev-charging-payments.html",
    "title": "Pod partners with Zapmap on public EV charging payments | Podpoint"
  },
  {
    "route": "/news02e4",
    "htmlPath": "news02e4.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/news2679",
    "htmlPath": "news2679.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/news4658",
    "htmlPath": "news4658.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/news9ba9",
    "htmlPath": "news9ba9.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/newsaf4d",
    "htmlPath": "newsaf4d.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/newsc575",
    "htmlPath": "newsc575.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/newsfdb0",
    "htmlPath": "newsfdb0.html",
    "title": "News | Podpoint"
  },
  {
    "route": "/offers/discounts",
    "htmlPath": "offers/discounts.html",
    "title": "EV Charger Discounts, Key Worker, Student & More | Pod"
  },
  {
    "route": "/order-now",
    "htmlPath": "order-now.html",
    "title": "Demander un devis | Pod"
  },
  {
    "route": "/order-now33f6",
    "htmlPath": "order-now33f6.html",
    "title": "Order now | Pod"
  },
  {
    "route": "/pod-power-edf-claims-explained",
    "htmlPath": "pod-power-edf-claims-explained.html",
    "title": "Pod Power substantiation | Pod"
  },
  {
    "route": "/pod-pros",
    "htmlPath": "pod-pros.html",
    "title": "Pod Pros Installer Loyalty | Pod"
  },
  {
    "route": "/pod-rewards",
    "htmlPath": "pod-rewards.html",
    "title": "Pod | Rewards for smart charging"
  },
  {
    "route": "/products/app",
    "htmlPath": "products/app.html",
    "title": "Pod Home App | Podpoint"
  },
  {
    "route": "/products/array",
    "htmlPath": "products/array.html",
    "title": "Array Charging | Podpoint"
  },
  {
    "route": "/products/domestic-installer-guidance",
    "htmlPath": "products/domestic-installer-guidance.html",
    "title": "Domestic Installer Guidance | Pod"
  },
  {
    "route": "/products/ev-zones",
    "htmlPath": "products/ev-zones.html",
    "title": "EV Zones | Podpoint"
  },
  {
    "route": "/products/media",
    "htmlPath": "products/media.html",
    "title": "Media Chargers | Podpoint"
  },
  {
    "route": "/products/plug-power",
    "htmlPath": "products/plug-power.html",
    "title": "Plug & Power Bundle From &pound;499 Upfront| Pod"
  },
  {
    "route": "/products/pod-drive",
    "htmlPath": "products/pod-drive.html",
    "title": "Pod Drive | Pod"
  },
  {
    "route": "/products/site-management-service",
    "htmlPath": "products/site-management-service.html",
    "title": "Site Management Service | Podpoint"
  },
  {
    "route": "/products/solo-business",
    "htmlPath": "products/solo-business.html",
    "title": "Solo 3S for Business | Podpoint"
  },
  {
    "route": "/products/solo-home-ev-charger",
    "htmlPath": "products/solo-home-ev-charger.html",
    "title": "Award Winning Home EV Charger with Trusted Warranty | Pod"
  },
  {
    "route": "/products/twin",
    "htmlPath": "products/twin.html",
    "title": "Twin Charger Product Page | Podpoint"
  },
  {
    "route": "/products/velocity-plus",
    "htmlPath": "products/velocity-plus.html",
    "title": "Velocity+ Charger Product Page | Podpoint"
  },
  {
    "route": "/public-charging-zapmap",
    "htmlPath": "public-charging-zapmap.html",
    "title": "Public Charging with Zapmap | Podpoint"
  },
  {
    "route": "/reports",
    "htmlPath": "reports.html",
    "title": "Reports | Podpoint"
  },
  {
    "route": "/security",
    "htmlPath": "security.html",
    "title": "Security | Podpoint"
  },
  {
    "route": "/sitemap",
    "htmlPath": "sitemap.html",
    "title": "Sitemap | Podpoint"
  },
  {
    "route": "/solutions/network",
    "htmlPath": "solutions/network.html",
    "title": "Pod Point network | Podpoint"
  },
  {
    "route": "/solutions/rapid-charging",
    "htmlPath": "solutions/rapid-charging.html",
    "title": "Rapid Public Charging | Pod Energy"
  },
  {
    "route": "/technical/hardware",
    "htmlPath": "technical/hardware.html",
    "title": "Technical Documents | Podpoint"
  },
  {
    "route": "/technical/installation",
    "htmlPath": "technical/installation.html",
    "title": "Installation documents | Podpoint"
  },
  {
    "route": "/terms-updates-directory",
    "htmlPath": "terms-updates-directory.html",
    "title": "Pod Point General Terms and Conditions for Consumers Summary of Updates | Podpoint"
  },
  {
    "route": "/vehicle-guides",
    "htmlPath": "vehicle-guides.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guides/alpine/a390",
    "htmlPath": "vehicle-guides/alpine/a390.html",
    "title": "A390 | Podpoint"
  },
  {
    "route": "/vehicle-guides/bmw/330e",
    "htmlPath": "vehicle-guides/bmw/330e.html",
    "title": "330e | Podpoint"
  },
  {
    "route": "/vehicle-guides/bmw/x1",
    "htmlPath": "vehicle-guides/bmw/x1.html",
    "title": "X1 | Podpoint"
  },
  {
    "route": "/vehicle-guides/changan/deepal-s07",
    "htmlPath": "vehicle-guides/changan/deepal-s07.html",
    "title": "Deepal S07 | Podpoint"
  },
  {
    "route": "/vehicle-guides/ford/kuga",
    "htmlPath": "vehicle-guides/ford/kuga.html",
    "title": "Kuga | Podpoint"
  },
  {
    "route": "/vehicle-guides/jaecoo/5-ev",
    "htmlPath": "vehicle-guides/jaecoo/5-ev.html",
    "title": "5 EV | Podpoint"
  },
  {
    "route": "/vehicle-guides/mercedes-benz/cla-shooting-brake",
    "htmlPath": "vehicle-guides/mercedes-benz/cla-shooting-brake.html",
    "title": "CLA Shooting Brake | Podpoint"
  },
  {
    "route": "/vehicle-guides/porsche/cayenne",
    "htmlPath": "vehicle-guides/porsche/cayenne.html",
    "title": "Cayenne | Podpoint"
  },
  {
    "route": "/vehicle-guides/renault/twingo",
    "htmlPath": "vehicle-guides/renault/twingo.html",
    "title": "Twingo | Podpoint"
  },
  {
    "route": "/vehicle-guides/tesla/model-3",
    "htmlPath": "vehicle-guides/tesla/model-3.html",
    "title": "Model 3 | Podpoint"
  },
  {
    "route": "/vehicle-guides/volkswagen/e-transporter-kombi",
    "htmlPath": "vehicle-guides/volkswagen/e-transporter-kombi.html",
    "title": "e-Transporter Kombi | Podpoint"
  },
  {
    "route": "/vehicle-guides/volkswagen/e-transporter-shuttle",
    "htmlPath": "vehicle-guides/volkswagen/e-transporter-shuttle.html",
    "title": "e-Transporter Shuttle | Podpoint"
  },
  {
    "route": "/vehicle-guides02e4",
    "htmlPath": "vehicle-guides02e4.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guides235c",
    "htmlPath": "vehicle-guides235c.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guides2679",
    "htmlPath": "vehicle-guides2679.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guides4658",
    "htmlPath": "vehicle-guides4658.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guides9ba9",
    "htmlPath": "vehicle-guides9ba9.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guidesaf4d",
    "htmlPath": "vehicle-guidesaf4d.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guidesc575",
    "htmlPath": "vehicle-guidesc575.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guidesce37",
    "htmlPath": "vehicle-guidesce37.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guidesfdb0",
    "htmlPath": "vehicle-guidesfdb0.html",
    "title": "Vehicle guides | Podpoint"
  },
  {
    "route": "/vehicle-guidesfdfa",
    "htmlPath": "vehicle-guidesfdfa.html",
    "title": "Vehicle guides | Podpoint"
  }
]
